#!/bin/bash
#
# bootstrap installs things.

# Change default shell to zsh

if [ "$SHELL" != "/bin/zsh" ]
then
  chsh -s /bin/zsh
fi 

DOTFILES_ROOT=$(pwd)

set -e

echo ''

info () {
  printf "  [ \033[00;34m..\033[0m ] %s" "$1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] %s " "$1"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s1\n" "$1"
  echo ''
  exit
}

link_file () {
  local src dst overwrite backup skip action

  src=$1
  dst=$2

  if [ -f "$dst" ] || [ -d "$dst" ] || [ -L "$dst" ]
  then

     if [ "$overwrite_all" = "false" ] && [ "$backup_all" = "false" ] && [ "$skip_all" = "false" ]
     then
 
        local currentSrc
        currentSrc="$(readlink "$dst")"
 
        if [ "$currentSrc" = "$src" ]
        then
 
          skip=true;
 
        else
 
          user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
          [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
          read -r -n 1 action
 
          case "$action" in
            o )
              overwrite=true;;
            O )
              overwrite_all=true;;
            b )
              backup=true;;
            B )
              backup_all=true;;
            s )
              skip=true;;
            S )
              skip_all=true;;
            * )
              ;;
          esac
 
        fi
 
     fi
 
     overwrite=${overwrite:-$overwrite_all}
     backup=${backup:-$backup_all}
     skip=${skip:-$skip_all}
 
     if [ "$overwrite" = "true" ]
     then
       rm -rf "$dst"
       success "removed $dst"
     fi
 
     if [ "$backup" = "true" ]
     then
       mv "$dst" "${dst}.backup"
       success "moved $dst to ${dst}.backup"
     fi
 
     if [ "$skip" = "true" ]
     then
       success "skipped $src"
     fi
   fi
 
   if [ "$skip" != "true" ]  # "false" or empty
   then
     ln -s "$1" "$2"
     success "linked $1 to $2"
  fi
}

install_dotfiles () {
  info 'installing dotfiles\n'

  local overwrite_all=false 
  local backup_all=false 
  local skip_all=false

  find "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -print0 |
    while IFS= read -r -d $'\0' line; do
      dst="$HOME/.$(basename "${line%.*}")"
      info "linking file $line to $dst"
      link_file "$line" "$dst"
    done
}

install_dotfiles

echo ''
echo '  All installed!'
